        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 14 19:26:16 2019
        MODULE WRITEVALUE__genmod
          INTERFACE 
            SUBROUTINE WRITEVALUE(NAME,VALUE)
              CHARACTER(LEN=10) :: NAME
              REAL(KIND=4) :: VALUE
            END SUBROUTINE WRITEVALUE
          END INTERFACE 
        END MODULE WRITEVALUE__genmod
