        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 12 13:43:57 2019
        MODULE CALL_SUB__genmod
          INTERFACE 
            SUBROUTINE CALL_SUB
            END SUBROUTINE CALL_SUB
          END INTERFACE 
        END MODULE CALL_SUB__genmod
