        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 15 19:49:07 2019
        MODULE GETSTRESS__genmod
          INTERFACE 
            SUBROUTINE GETSTRESS(DDSDDE,STRESS,DSTRAN,NTENS)
              INTEGER(KIND=4) :: NTENS
              REAL(KIND=8) :: DDSDDE(NTENS,NTENS)
              REAL(KIND=8) :: STRESS(NTENS)
              REAL(KIND=8) :: DSTRAN(NTENS)
            END SUBROUTINE GETSTRESS
          END INTERFACE 
        END MODULE GETSTRESS__genmod
