        !COMPILER-GENERATED INTERFACE MODULE: Sat Jul 13 22:05:48 2019
        MODULE WRITEVALUE__genmod
          INTERFACE 
            SUBROUTINE WRITEVALUE(NAME,VALUE)
              CHARACTER(LEN=10) :: NAME
              REAL(KIND=4) :: VALUE
            END SUBROUTINE WRITEVALUE
          END INTERFACE 
        END MODULE WRITEVALUE__genmod
