        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 08 22:55:05 2019
        MODULE SUB__genmod
          INTERFACE 
            SUBROUTINE SUB
            END SUBROUTINE SUB
          END INTERFACE 
        END MODULE SUB__genmod
